In [2]:
import pandas as pd
import numpy as np
import sqlite3
import os
import joblib

In [3]:
import sqlite3
import os

DB_PATH = os.path.join("database", "hospital.db")

conn = sqlite3.connect(DB_PATH)

print("Database connected successfully!")

Database connected successfully!

In [4]:
create_departments_table = """
CREATE TABLE IF NOT EXISTS departments (
    department_id INTEGER PRIMARY KEY AUTOINCREMENT,
    department_name TEXT NOT NULL UNIQUE,
    description TEXT
)
"""

conn.execute(create_departments_table)
conn.commit()

print("Departments table created successfully!")

Departments table created successfully!

In [ ]:
departments = [
    ("General Medicine", "Diagnosis and treatment of common medical conditions"),
    ("Cardiology", "Heart and cardiovascular related care"),
    ("Dermatology", "Skin, hair and nail related care"),
    ("Orthopedics", "Bone, joint and muscle related care"),
    ("Neurology", "Brain and nervous system related care"),
    ("Pediatrics", "Healthcare for children"),
    ("ENT", "Ear, nose and throat related care"),
    ("Ophthalmology", "Eye related care"),
    ("Gynecology", "Women's reproductive health care"),
    ("Gastroenterology", "Digestive system related care")
]

conn.executemany(
    "INSERT INTO departments (department_name, description) VALUES (?, ?)",
    departments
)

conn.commit()

print("Departments data inserted successfully!")

In [8]:
df_departments = pd.read_sql_query(
    "SELECT * FROM departments",
    conn
)

df_departments

,department_id,department_name,description
0,1,General Medicine,Diagnosis and treatment of common medical cond...
1,2,Cardiology,Heart and cardiovascular related care
2,3,Dermatology,"Skin, hair and nail related care"
3,4,Orthopedics,"Bone, joint and muscle related care"
4,5,Neurology,Brain and nervous system related care
5,6,Pediatrics,Healthcare for children
6,7,ENT,"Ear, nose and throat related care"
7,8,Ophthalmology,Eye related care
8,9,Gynecology,Women's reproductive health care
9,10,Gastroenterology,Digestive system related care

In [9]:
create_doctors_table = """
CREATE TABLE IF NOT EXISTS doctors (
    doctor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    doctor_name TEXT NOT NULL,
    specialization TEXT NOT NULL,
    department_id INTEGER NOT NULL,
    phone TEXT,
    email TEXT,
    room_number TEXT,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
)
"""

conn.execute(create_doctors_table)
conn.commit()

print("Doctors table created successfully!")

Doctors table created successfully!

In [10]:
doctors = [
    ("Dr. Rahul Patil", "General Physician", 1, "9876543210", "rahul@hospital.com", "OPD-01"),
    ("Dr. Sneha Joshi", "Cardiologist", 2, "9876543211", "sneha@hospital.com", "OPD-02"),
    ("Dr. Amit Shah", "Dermatologist", 3, "9876543212", "amit@hospital.com", "OPD-03"),
    ("Dr. Pooja More", "Orthopedic Surgeon", 4, "9876543213", "pooja@hospital.com", "OPD-04"),
    ("Dr. Kiran Desai", "Neurologist", 5, "9876543214", "kiran@hospital.com", "OPD-05"),
    ("Dr. Neha Kulkarni", "Pediatrician", 6, "9876543215", "neha@hospital.com", "OPD-06"),
    ("Dr. Rohan Patil", "ENT Specialist", 7, "9876543216", "rohan@hospital.com", "OPD-07"),
    ("Dr. Aarti Joshi", "Ophthalmologist", 8, "9876543217", "aarti@hospital.com", "OPD-08"),
    ("Dr. Priya Shah", "Gynecologist", 9, "9876543218", "priya@hospital.com", "OPD-09"),
    ("Dr. Sameer More", "Gastroenterologist", 10, "9876543219", "sameer@hospital.com", "OPD-10")
]

conn.executemany("""
    INSERT INTO doctors
    (doctor_name, specialization, department_id, phone, email, room_number)
    VALUES (?, ?, ?, ?, ?, ?)
""", doctors)

conn.commit()

print("Doctors data inserted successfully!")

Doctors data inserted successfully!

In [11]:
df_doctors = pd.read_sql_query("""
    SELECT 
        d.doctor_id,
        d.doctor_name,
        d.specialization,
        dep.department_name,
        d.phone,
        d.email,
        d.room_number
    FROM doctors d
    JOIN departments dep
    ON d.department_id = dep.department_id
""", conn)

df_doctors

,doctor_id,doctor_name,specialization,department_name,phone,email,room_number
0,1,Dr. Rahul Patil,General Physician,General Medicine,9876543210,rahul@hospital.com,OPD-01
1,2,Dr. Sneha Joshi,Cardiologist,Cardiology,9876543211,sneha@hospital.com,OPD-02
2,3,Dr. Amit Shah,Dermatologist,Dermatology,9876543212,amit@hospital.com,OPD-03
3,4,Dr. Pooja More,Orthopedic Surgeon,Orthopedics,9876543213,pooja@hospital.com,OPD-04
4,5,Dr. Kiran Desai,Neurologist,Neurology,9876543214,kiran@hospital.com,OPD-05
5,6,Dr. Neha Kulkarni,Pediatrician,Pediatrics,9876543215,neha@hospital.com,OPD-06
6,7,Dr. Rohan Patil,ENT Specialist,ENT,9876543216,rohan@hospital.com,OPD-07
7,8,Dr. Aarti Joshi,Ophthalmologist,Ophthalmology,9876543217,aarti@hospital.com,OPD-08
8,9,Dr. Priya Shah,Gynecologist,Gynecology,9876543218,priya@hospital.com,OPD-09
9,10,Dr. Sameer More,Gastroenterologist,Gastroenterology,9876543219,sameer@hospital.com,OPD-10
10,11,Dr. Rahul Patil,General Physician,General Medicine,9876543210,rahul@hospital.com,OPD-01
11,12,Dr. Sneha Joshi,Cardiologist,Cardiology,9876543211,sneha@hospital.com,OPD-02
12,13,Dr. Amit Shah,Dermatologist,Dermatology,9876543212,amit@hospital.com,OPD-03
13,14,Dr. Pooja More,Orthopedic Surgeon,Orthopedics,9876543213,pooja@hospital.com,OPD-04
14,15,Dr. Kiran Desai,Neurologist,Neurology,9876543214,kiran@hospital.com,OPD-05
15,16,Dr. Neha Kulkarni,Pediatrician,Pediatrics,9876543215,neha@hospital.com,OPD-06
16,17,Dr. Rohan Patil,ENT Specialist,ENT,9876543216,rohan@hospital.com,OPD-07
17,18,Dr. Aarti Joshi,Ophthalmologist,Ophthalmology,9876543217,aarti@hospital.com,OPD-08
18,19,Dr. Priya Shah,Gynecologist,Gynecology,9876543218,priya@hospital.com,OPD-09
19,20,Dr. Sameer More,Gastroenterologist,Gastroenterology,9876543219,sameer@hospital.com,OPD-10

In [12]:
create_shifts_table = """
CREATE TABLE IF NOT EXISTS doctor_shifts (
    shift_id INTEGER PRIMARY KEY AUTOINCREMENT,
    doctor_id INTEGER NOT NULL,
    duty_date TEXT NOT NULL,
    shift_name TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    status TEXT NOT NULL,
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
)
"""

conn.execute(create_shifts_table)
conn.commit()

print("Doctor shifts table created successfully!")

Doctor shifts table created successfully!

In [13]:
from datetime import date

today = date.today().isoformat()

print("Duty Date:", today)

Duty Date: 2026-08-24

In [14]:
shift_data = [
    (1, today, "Morning", "08:00", "14:00", "Available"),
    (2, today, "Morning", "08:00", "14:00", "On Duty"),
    (3, today, "Morning", "08:00", "14:00", "Available"),
    (4, today, "Evening", "14:00", "20:00", "Available"),
    (5, today, "Evening", "14:00", "20:00", "On Duty"),
    (6, today, "Evening", "14:00", "20:00", "Available"),
    (7, today, "Night", "20:00", "08:00", "Available"),
    (8, today, "Night", "20:00", "08:00", "On Duty"),
    (9, today, "Morning", "08:00", "14:00", "Available"),
    (10, today, "Evening", "14:00", "20:00", "Available")
]

conn.executemany("""
    INSERT INTO doctor_shifts
    (doctor_id, duty_date, shift_name, start_time, end_time, status)
    VALUES (?, ?, ?, ?, ?, ?)
""", shift_data)

conn.commit()

print("Doctor shift data inserted successfully!")

Doctor shift data inserted successfully!

In [15]:
df_shifts = pd.read_sql_query("""
    SELECT
        ds.shift_id,
        d.doctor_name,
        d.specialization,
        dep.department_name,
        ds.duty_date,
        ds.shift_name,
        ds.start_time,
        ds.end_time,
        ds.status,
        d.room_number
    FROM doctor_shifts ds
    JOIN doctors d
        ON ds.doctor_id = d.doctor_id
    JOIN departments dep
        ON d.department_id = dep.department_id
    ORDER BY ds.shift_name, ds.start_time
""", conn)

df_shifts

,shift_id,doctor_name,specialization,department_name,duty_date,shift_name,start_time,end_time,status,room_number
0,4,Dr. Pooja More,Orthopedic Surgeon,Orthopedics,2026-08-22,Evening,14:00,20:00,Available,OPD-04
1,5,Dr. Kiran Desai,Neurologist,Neurology,2026-08-22,Evening,14:00,20:00,On Duty,OPD-05
2,6,Dr. Neha Kulkarni,Pediatrician,Pediatrics,2026-08-22,Evening,14:00,20:00,Available,OPD-06
3,10,Dr. Sameer More,Gastroenterologist,Gastroenterology,2026-08-22,Evening,14:00,20:00,Available,OPD-10
4,14,Dr. Pooja More,Orthopedic Surgeon,Orthopedics,2026-08-24,Evening,14:00,20:00,Available,OPD-04
5,15,Dr. Kiran Desai,Neurologist,Neurology,2026-08-24,Evening,14:00,20:00,On Duty,OPD-05
6,16,Dr. Neha Kulkarni,Pediatrician,Pediatrics,2026-08-24,Evening,14:00,20:00,Available,OPD-06
7,20,Dr. Sameer More,Gastroenterologist,Gastroenterology,2026-08-24,Evening,14:00,20:00,Available,OPD-10
8,1,Dr. Rahul Patil,General Physician,General Medicine,2026-08-22,Morning,08:00,14:00,Available,OPD-01
9,2,Dr. Sneha Joshi,Cardiologist,Cardiology,2026-08-22,Morning,08:00,14:00,On Duty,OPD-02
10,3,Dr. Amit Shah,Dermatologist,Dermatology,2026-08-22,Morning,08:00,14:00,Available,OPD-03
11,9,Dr. Priya Shah,Gynecologist,Gynecology,2026-08-22,Morning,08:00,14:00,Available,OPD-09
12,11,Dr. Rahul Patil,General Physician,General Medicine,2026-08-24,Morning,08:00,14:00,Available,OPD-01
13,12,Dr. Sneha Joshi,Cardiologist,Cardiology,2026-08-24,Morning,08:00,14:00,On Duty,OPD-02
14,13,Dr. Amit Shah,Dermatologist,Dermatology,2026-08-24,Morning,08:00,14:00,Available,OPD-03
15,19,Dr. Priya Shah,Gynecologist,Gynecology,2026-08-24,Morning,08:00,14:00,Available,OPD-09
16,7,Dr. Rohan Patil,ENT Specialist,ENT,2026-08-22,Night,20:00,08:00,Available,OPD-07
17,8,Dr. Aarti Joshi,Ophthalmologist,Ophthalmology,2026-08-22,Night,20:00,08:00,On Duty,OPD-08
18,17,Dr. Rohan Patil,ENT Specialist,ENT,2026-08-24,Night,20:00,08:00,Available,OPD-07
19,18,Dr. Aarti Joshi,Ophthalmologist,Ophthalmology,2026-08-24,Night,20:00,08:00,On Duty,OPD-08

In [16]:
available_doctors = pd.read_sql_query("""
    SELECT
        d.doctor_name,
        d.specialization,
        dep.department_name,
        ds.shift_name,
        ds.start_time,
        ds.end_time,
        d.room_number,
        ds.status
    FROM doctor_shifts ds
    JOIN doctors d
        ON ds.doctor_id = d.doctor_id
    JOIN departments dep
        ON d.department_id = dep.department_id
    WHERE ds.duty_date = ?
      AND ds.status = 'Available'
    ORDER BY ds.start_time
""", conn, params=(today,))

available_doctors

,doctor_name,specialization,department_name,shift_name,start_time,end_time,room_number,status
0,Dr. Rahul Patil,General Physician,General Medicine,Morning,08:00,14:00,OPD-01,Available
1,Dr. Amit Shah,Dermatologist,Dermatology,Morning,08:00,14:00,OPD-03,Available
2,Dr. Priya Shah,Gynecologist,Gynecology,Morning,08:00,14:00,OPD-09,Available
3,Dr. Pooja More,Orthopedic Surgeon,Orthopedics,Evening,14:00,20:00,OPD-04,Available
4,Dr. Neha Kulkarni,Pediatrician,Pediatrics,Evening,14:00,20:00,OPD-06,Available
5,Dr. Sameer More,Gastroenterologist,Gastroenterology,Evening,14:00,20:00,OPD-10,Available
6,Dr. Rohan Patil,ENT Specialist,ENT,Night,20:00,08:00,OPD-07,Available

In [17]:
create_patients_table = """
CREATE TABLE IF NOT EXISTS patients (
    patient_id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_name TEXT NOT NULL,
    age INTEGER,
    gender TEXT,
    phone TEXT,
    address TEXT,
    symptoms TEXT,
    registration_date TEXT
)
"""

conn.execute(create_patients_table)
conn.commit()

print("Patients table created successfully!")

Patients table created successfully!

In [18]:
df_departments = pd.read_sql_query(
    "SELECT * FROM departments",
    conn
)

df_departments

,department_id,department_name,description
0,1,General Medicine,Diagnosis and treatment of common medical cond...
1,2,Cardiology,Heart and cardiovascular related care
2,3,Dermatology,"Skin, hair and nail related care"
3,4,Orthopedics,"Bone, joint and muscle related care"
4,5,Neurology,Brain and nervous system related care
5,6,Pediatrics,Healthcare for children
6,7,ENT,"Ear, nose and throat related care"
7,8,Ophthalmology,Eye related care
8,9,Gynecology,Women's reproductive health care
9,10,Gastroenterology,Digestive system related care

In [19]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='patients'",
    conn
)

       name
0  patients

In [20]:
from datetime import date

patients = [
    ("Aarav Patil", 25, "Male", "9876500001", "Kolhapur",
     "skin itching and red rashes", date.today().isoformat()),

    ("Sneha More", 32, "Female", "9876500002", "Belagavi",
     "stomach pain and digestive problem", date.today().isoformat()),

    ("Rohan Joshi", 45, "Male", "9876500003", "Sangli",
     "joint pain and difficulty walking", date.today().isoformat()),

    ("Priya Kulkarni", 8, "Female", "9876500004", "Kolhapur",
     "fever and cough", date.today().isoformat()),

    ("Amit Desai", 55, "Male", "9876500005", "Belagavi",
     "chest pain and breathing difficulty", date.today().isoformat())
]

conn.executemany("""
    INSERT INTO patients
    (patient_name, age, gender, phone, address, symptoms, registration_date)
    VALUES (?, ?, ?, ?, ?, ?, ?)
""", patients)

conn.commit()

print("Patient data inserted successfully!")

Patient data inserted successfully!

In [21]:
df_patients = pd.read_sql_query(
    "SELECT * FROM patients",
    conn
)

df_patients

,patient_id,patient_name,age,gender,phone,address,symptoms,registration_date
0,1,Aarav Patil,25,Male,9876500001,Kolhapur,skin itching and red rashes,2026-08-24
1,2,Sneha More,32,Female,9876500002,Belagavi,stomach pain and digestive problem,2026-08-24
2,3,Rohan Joshi,45,Male,9876500003,Sangli,joint pain and difficulty walking,2026-08-24
3,4,Priya Kulkarni,8,Female,9876500004,Kolhapur,fever and cough,2026-08-24
4,5,Amit Desai,55,Male,9876500005,Belagavi,chest pain and breathing difficulty,2026-08-24

In [22]:
create_history_table = """
CREATE TABLE IF NOT EXISTS patient_history (
    history_id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    doctor_id INTEGER,
    visit_date TEXT NOT NULL,
    department TEXT,
    symptoms TEXT,
    notes TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
)
"""

conn.execute(create_history_table)
conn.commit()

print("Patient history table created successfully!")

Patient history table created successfully!

In [23]:
history_data = [
    (1, 3, "2026-08-20", "Dermatology",
     "skin itching and red rashes",
     "Skin examination advised"),

    (2, 10, "2026-08-18", "Gastroenterology",
     "stomach pain and digestive problem",
     "Dietary consultation advised"),

    (3, 4, "2026-08-15", "Orthopedics",
     "joint pain and difficulty walking",
     "Physical examination advised"),

    (4, 6, "2026-08-21", "Pediatrics",
     "fever and cough",
     "General check-up completed"),

    (5, 2, "2026-08-19", "Cardiology",
     "chest pain and breathing difficulty",
     "Cardiology consultation advised")
]

conn.executemany("""
    INSERT INTO patient_history
    (patient_id, doctor_id, visit_date, department, symptoms, notes)
    VALUES (?, ?, ?, ?, ?, ?)
""", history_data)

conn.commit()

print("Patient history data inserted successfully!")

Patient history data inserted successfully!

In [24]:
df_history = pd.read_sql_query("""
    SELECT
        ph.history_id,
        p.patient_name,
        d.doctor_name,
        ph.visit_date,
        ph.department,
        ph.symptoms,
        ph.notes
    FROM patient_history ph
    JOIN patients p
        ON ph.patient_id = p.patient_id
    LEFT JOIN doctors d
        ON ph.doctor_id = d.doctor_id
    ORDER BY ph.visit_date DESC
""", conn)

df_history

,history_id,patient_name,doctor_name,visit_date,department,symptoms,notes
0,4,Priya Kulkarni,Dr. Neha Kulkarni,2026-08-21,Pediatrics,fever and cough,General check-up completed
1,1,Aarav Patil,Dr. Amit Shah,2026-08-20,Dermatology,skin itching and red rashes,Skin examination advised
2,5,Amit Desai,Dr. Sneha Joshi,2026-08-19,Cardiology,chest pain and breathing difficulty,Cardiology consultation advised
3,2,Sneha More,Dr. Sameer More,2026-08-18,Gastroenterology,stomach pain and digestive problem,Dietary consultation advised
4,3,Rohan Joshi,Dr. Pooja More,2026-08-15,Orthopedics,joint pain and difficulty walking,Physical examination advised

In [26]:
pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table' AND name='appointments'",
    conn
)

Empty DataFrame
Columns: [name]
Index: []

In [27]:
create_appointments_table = """
CREATE TABLE IF NOT EXISTS appointments (
    appointment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    patient_id INTEGER NOT NULL,
    doctor_id INTEGER NOT NULL,
    appointment_date TEXT NOT NULL,
    appointment_time TEXT NOT NULL,
    status TEXT NOT NULL,
    reason TEXT,
    FOREIGN KEY (patient_id) REFERENCES patients(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(doctor_id)
)
"""

conn.execute(create_appointments_table)
conn.commit()

print("Appointments table created successfully!")

Appointments table created successfully!

In [28]:
appointment_data = [
    (1, 3, "2026-08-24", "09:00", "Confirmed", "Skin consultation"),
    (2, 10, "2026-08-24", "15:00", "Confirmed", "Stomach problem"),
    (3, 4, "2026-08-24", "16:00", "Pending", "Joint pain"),
    (4, 6, "2026-08-24", "17:00", "Confirmed", "Fever and cough"),
    (5, 2, "2026-08-24", "09:30", "Pending", "Chest discomfort")
]

conn.executemany("""
    INSERT INTO appointments
    (patient_id, doctor_id, appointment_date, appointment_time, status, reason)
    VALUES (?, ?, ?, ?, ?, ?)
""", appointment_data)

conn.commit()

print("Appointment data inserted successfully!")

Appointment data inserted successfully!

In [29]:
df_appointments = pd.read_sql_query("""
    SELECT
        a.appointment_id,
        p.patient_name,
        d.doctor_name,
        dep.department_name,
        a.appointment_date,
        a.appointment_time,
        a.status,
        a.reason
    FROM appointments a
    JOIN patients p
        ON a.patient_id = p.patient_id
    JOIN doctors d
        ON a.doctor_id = d.doctor_id
    JOIN departments dep
        ON d.department_id = dep.department_id
    ORDER BY a.appointment_date, a.appointment_time
""", conn)

df_appointments

,appointment_id,patient_name,doctor_name,department_name,appointment_date,appointment_time,status,reason
0,1,Aarav Patil,Dr. Amit Shah,Dermatology,2026-08-24,09:00,Confirmed,Skin consultation
1,5,Amit Desai,Dr. Sneha Joshi,Cardiology,2026-08-24,09:30,Pending,Chest discomfort
2,2,Sneha More,Dr. Sameer More,Gastroenterology,2026-08-24,15:00,Confirmed,Stomach problem
3,3,Rohan Joshi,Dr. Pooja More,Orthopedics,2026-08-24,16:00,Pending,Joint pain
4,4,Priya Kulkarni,Dr. Neha Kulkarni,Pediatrics,2026-08-24,17:00,Confirmed,Fever and cough

In [30]:
df_appointments = pd.read_sql_query("""
    SELECT
        a.appointment_id,
        p.patient_name,
        d.doctor_name,
        dep.department_name,
        a.appointment_date,
        a.appointment_time,
        a.status,
        a.reason
    FROM appointments a
    JOIN patients p
        ON a.patient_id = p.patient_id
    JOIN doctors d
        ON a.doctor_id = d.doctor_id
    JOIN departments dep
        ON d.department_id = dep.department_id
    ORDER BY a.appointment_date, a.appointment_time
""", conn)

df_appointments

,appointment_id,patient_name,doctor_name,department_name,appointment_date,appointment_time,status,reason
0,1,Aarav Patil,Dr. Amit Shah,Dermatology,2026-08-24,09:00,Confirmed,Skin consultation
1,5,Amit Desai,Dr. Sneha Joshi,Cardiology,2026-08-24,09:30,Pending,Chest discomfort
2,2,Sneha More,Dr. Sameer More,Gastroenterology,2026-08-24,15:00,Confirmed,Stomach problem
3,3,Rohan Joshi,Dr. Pooja More,Orthopedics,2026-08-24,16:00,Pending,Joint pain
4,4,Priya Kulkarni,Dr. Neha Kulkarni,Pediatrics,2026-08-24,17:00,Confirmed,Fever and cough

In [31]:
create_services_table = """
CREATE TABLE IF NOT EXISTS services (
    service_id INTEGER PRIMARY KEY AUTOINCREMENT,
    service_name TEXT NOT NULL UNIQUE,
    department_id INTEGER,
    description TEXT,
    availability TEXT,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
)
"""

conn.execute(create_services_table)
conn.commit()

print("Services table created successfully!")

Services table created successfully!

In [32]:
services = [
    ("Blood Test", 1, "Basic blood testing and laboratory analysis", "Available"),
    ("ECG", 2, "Electrocardiogram test for heart activity", "Available"),
    ("Skin Test", 3, "Basic dermatology related diagnostic tests", "Available"),
    ("X-Ray", 4, "Bone and joint imaging service", "Available"),
    ("MRI Scan", 5, "Brain and nervous system imaging", "Available"),
    ("Child Health Checkup", 6, "Routine health checkup for children", "Available"),
    ("ENT Examination", 7, "Ear, nose and throat examination", "Available"),
    ("Eye Test", 8, "Vision and eye examination", "Available"),
    ("Women's Health Checkup", 9, "Gynecology related health services", "Available"),
    ("Ultrasound", 10, "Ultrasound and digestive system diagnostic support", "Available")
]

conn.executemany("""
    INSERT INTO services
    (service_name, department_id, description, availability)
    VALUES (?, ?, ?, ?)
""", services)

conn.commit()

print("Hospital services data inserted successfully!")

Hospital services data inserted successfully!

In [33]:
df_services = pd.read_sql_query("""
    SELECT
        s.service_id,
        s.service_name,
        dep.department_name,
        s.description,
        s.availability
    FROM services s
    LEFT JOIN departments dep
        ON s.department_id = dep.department_id
    ORDER BY s.service_id
""", conn)

df_services

,service_id,service_name,department_name,description,availability
0,1,Blood Test,General Medicine,Basic blood testing and laboratory analysis,Available
1,2,ECG,Cardiology,Electrocardiogram test for heart activity,Available
2,3,Skin Test,Dermatology,Basic dermatology related diagnostic tests,Available
3,4,X-Ray,Orthopedics,Bone and joint imaging service,Available
4,5,MRI Scan,Neurology,Brain and nervous system imaging,Available
5,6,Child Health Checkup,Pediatrics,Routine health checkup for children,Available
6,7,ENT Examination,ENT,"Ear, nose and throat examination",Available
7,8,Eye Test,Ophthalmology,Vision and eye examination,Available
8,9,Women's Health Checkup,Gynecology,Gynecology related health services,Available
9,10,Ultrasound,Gastroenterology,Ultrasound and digestive system diagnostic sup...,Available

In [1]:
import pandas as pd

original_data = pd.read_csv("data/original dataset.csv")

print("Dataset loaded successfully!")
print("Rows:", original_data.shape[0])
print("Columns:", original_data.shape[1])

original_data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/original dataset.csv'

In [2]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles and folders here:")
print(os.listdir())

Current folder:
C:\Users\DELL\PythonLibraries\hospital management and recommendation system

Files and folders here:
['.ipynb_checkpoints', 'data', 'database', 'hospital management.ipynb', 'model']

In [3]:
import os

print(os.listdir("data"))

['.ipynb_checkpoints', 'Disease_Description.csv', 'Doctor_Specialist.csv', 'Doctor_Versus_Disease.csv', 'Original_Dataset.csv', 'Specialist.xlsx', 'Symptom_Weights.csv']

In [4]:
import pandas as pd

original_data = pd.read_csv("data/Original_Dataset.csv")

print("Dataset loaded successfully!")
print("Rows:", original_data.shape[0])
print("Columns:", original_data.shape[1])

original_data.head()

Dataset loaded successfully!
Rows: 4920
Columns: 18

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(original_data.columns.tolist())
original_data.info()

['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4', 'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9', 'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14', 'Symptom_15', 'Symptom_16', 'Symptom_17']
<class 'pandas.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Disease     4920 non-null   str
 1   Symptom_1   4920 non-null   str
 2   Symptom_2   4920 non-null   str
 3   Symptom_3   4920 non-null   str
 4   Symptom_4   4572 non-null   str
 5   Symptom_5   3714 non-null   str
 6   Symptom_6   2934 non-null   str
 7   Symptom_7   2268 non-null   str
 8   Symptom_8   1944 non-null   str
 9   Symptom_9   1692 non-null   str
 10  Symptom_10  1512 non-null   str
 11  Symptom_11  1194 non-null   str
 12  Symptom_12  744 non-null    str
 13  Symptom_13  504 non-null    str
 14  Symptom_14  306 non-null    str
 15  Symptom_15  240 non-null    str
 16  Symptom_16  192 non-null    str
 17  Symptom_17  72 non-null     str
dtypes: str(18)
memory usage: 1.2 MB

In [6]:
# Create a copy so that original dataset remains safe
df_ml = original_data.copy()

# Replace missing values with empty text
df_ml = df_ml.fillna("")

print("Missing values handled successfully!")

print("\nRemaining missing values:")
print(df_ml.isnull().sum().sum())

Missing values handled successfully!

Remaining missing values:
0

In [7]:
# Get all symptom columns
symptom_columns = [
    col for col in df_ml.columns
    if col.startswith("Symptom_")
]

# Combine all symptoms into one text column
df_ml["All_Symptoms"] = df_ml[symptom_columns].apply(
    lambda row: " ".join(
        str(symptom).strip().replace("_", " ")
        for symptom in row
        if str(symptom).strip() != ""
    ),
    axis=1
)

# Display the result
df_ml[["Disease", "All_Symptoms"]].head()

            Disease                                       All_Symptoms
0  Fungal infection  itching skin rash nodal skin eruptions dischro...
1  Fungal infection  skin rash nodal skin eruptions dischromic  pat...
2  Fungal infection   itching nodal skin eruptions dischromic  patches
3  Fungal infection              itching skin rash dischromic  patches
4  Fungal infection             itching skin rash nodal skin eruptions

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(df_ml["All_Symptoms"])
y = df_ml["Disease"]

print("X shape:", X.shape)
print("Number of diseases:", y.nunique())

X shape: (4920, 208)
Number of diseases: 41

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training records:", X_train.shape[0])
print("Testing records:", X_test.shape[0])

Training records: 3936
Testing records: 984

In [10]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

print("ML model trained successfully!")

ML model trained successfully!

In [11]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

Model Accuracy: 100.0 %

In [12]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        24
                                   AIDS       1.00      1.00      1.00        24
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        24
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        24
                       Bronchial Asthma       1.00      1.00      1.00        24
                   Cervical spondylosis       1.00      1.00      1.00        24
                            Chicken pox       1.00      1.00      1.00        24
                    Chronic cholestasis       1.00      1.00      1.00        24
                            Common Cold       1.00      1.00      1.00        24
                                 Dengue       1.00      1.00      1.00        24
                              Diabetes        1.00      1.00      1.00        24
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00        24
                          Drug Reaction       1.00      1.00      1.00        24
                       Fungal infection       1.00      1.00      1.00        24
                                   GERD       1.00      1.00      1.00        24
                        Gastroenteritis       1.00      1.00      1.00        24
                           Heart attack       1.00      1.00      1.00        24
                            Hepatitis B       1.00      1.00      1.00        24
                            Hepatitis C       1.00      1.00      1.00        24
                            Hepatitis D       1.00      1.00      1.00        24
                            Hepatitis E       1.00      1.00      1.00        24
                          Hypertension        1.00      1.00      1.00        24
                        Hyperthyroidism       1.00      1.00      1.00        24
                           Hypoglycemia       1.00      1.00      1.00        24
                         Hypothyroidism       1.00      1.00      1.00        24
                               Impetigo       1.00      1.00      1.00        24
                               Jaundice       1.00      1.00      1.00        24
                                Malaria       1.00      1.00      1.00        24
                               Migraine       1.00      1.00      1.00        24
                        Osteoarthristis       1.00      1.00      1.00        24
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        24
                    Peptic ulcer diseae       1.00      1.00      1.00        24
                              Pneumonia       1.00      1.00      1.00        24
                              Psoriasis       1.00      1.00      1.00        24
                           Tuberculosis       1.00      1.00      1.00        24
                                Typhoid       1.00      1.00      1.00        24
                Urinary tract infection       1.00      1.00      1.00        24
                         Varicose veins       1.00      1.00      1.00        24
                            hepatitis A       1.00      1.00      1.00        24

                               accuracy                           1.00       984
                              macro avg       1.00      1.00      1.00       984
                           weighted avg       1.00      1.00      1.00       984

In [13]:
print("Total records:", len(df_ml))

duplicates = df_ml.duplicated(
    subset=["Disease", "All_Symptoms"]
).sum()

print("Duplicate records:", duplicates)

Total records: 4920
Duplicate records: 4616

In [14]:
df_clean = df_ml.drop_duplicates(
    subset=["Disease", "All_Symptoms"]
).reset_index(drop=True)

print("Original records:", len(df_ml))
print("After removing duplicates:", len(df_clean))

Original records: 4920
After removing duplicates: 304

In [15]:
# Create TF-IDF features from the clean dataset

X_clean = vectorizer.fit_transform(df_clean["All_Symptoms"])
y_clean = df_clean["Disease"]

print("Clean X shape:", X_clean.shape)
print("Number of diseases:", y_clean.nunique())

Clean X shape: (304, 208)
Number of diseases: 41

In [16]:
X_train_clean, X_test_clean, y_train_clean, y_test_clean = train_test_split(
    X_clean,
    y_clean,
    test_size=0.20,
    random_state=42,
    stratify=y_clean
)

print("Training records:", X_train_clean.shape[0])
print("Testing records:", X_test_clean.shape[0])

Training records: 243
Testing records: 61

In [17]:
from sklearn.linear_model import LogisticRegression

clean_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

clean_model.fit(X_train_clean, y_train_clean)

print("Clean ML model trained successfully!")

Clean ML model trained successfully!

In [18]:
from sklearn.metrics import accuracy_score

y_pred_clean = clean_model.predict(X_test_clean)

clean_accuracy = accuracy_score(
    y_test_clean,
    y_pred_clean
)

print("Clean Model Accuracy:", round(clean_accuracy * 100, 2), "%")

Clean Model Accuracy: 100.0 %

In [19]:
doctor_specialist = pd.read_csv("data/Doctor_Specialist.csv")

print("Rows:", doctor_specialist.shape[0])
print("Columns:", doctor_specialist.shape[1])

doctor_specialist.head()

Rows: 19
Columns: 1

    Doctor Specialist
0       Dermatologist
1           Allergist
2  Gastroenterologist
3        Hepatologist
4         Osteopathic

In [21]:
doctor_disease = pd.read_csv(
    "data/Doctor_Versus_Disease.csv",
    encoding="latin1"
)

print("Rows:", doctor_disease.shape[0])
print("Columns:", doctor_disease.shape[1])

doctor_disease.head(10)

Rows: 40
Columns: 2

      Drug Reaction        Allergist
0           Allergy        Allergist
1     Hypertension      Cardiologist
2      Heart attack     Cardiologist
3         Psoriasis    Dermatologist
4       Chicken pox    Dermatologist
5              Acne    Dermatologist
6          Impetigo    Dermatologist
7  Fungal infection    Dermatologist
8    Hypothyroidism  Endocrinologist
9         Diabetes   Endocrinologist

In [22]:
doctor_disease.columns = ["Disease", "Specialist"]

print(doctor_disease.head(10))

            Disease       Specialist
0           Allergy        Allergist
1     Hypertension      Cardiologist
2      Heart attack     Cardiologist
3         Psoriasis    Dermatologist
4       Chicken pox    Dermatologist
5              Acne    Dermatologist
6          Impetigo    Dermatologist
7  Fungal infection    Dermatologist
8    Hypothyroidism  Endocrinologist
9         Diabetes   Endocrinologist

In [23]:
disease_to_specialist = dict(
    zip(
        doctor_disease["Disease"],
        doctor_disease["Specialist"]
    )
)

print("Total disease-specialist mappings:", len(disease_to_specialist))

print("\nSample mappings:")
for disease, specialist in list(disease_to_specialist.items())[:10]:
    print(f"{disease} → {specialist}")

Total disease-specialist mappings: 40

Sample mappings:
Allergy → Allergist
Hypertension  → Cardiologist
Heart attack → Cardiologist
Psoriasis → Dermatologist
Chicken pox → Dermatologist
Acne → Dermatologist
Impetigo → Dermatologist
Fungal infection → Dermatologist
Hypothyroidism → Endocrinologist
Diabetes  → Endocrinologist

In [24]:
all_diseases = set(y_clean.unique())
mapped_diseases = set(disease_to_specialist.keys())

missing_diseases = sorted(all_diseases - mapped_diseases)

print("Diseases without specialist mapping:")
print(missing_diseases)

Diseases without specialist mapping:
['Drug Reaction']

In [25]:
print("Available Specialists:")
print(sorted(doctor_disease["Specialist"].dropna().unique()))

Available Specialists:
['Allergist', 'Cardiologist', 'Dermatologist', 'Endocrinologist', 'Gastroenterologist', 'Gastroenterologist\xa0', 'Gynecologist', 'Hepatologist', 'Internal Medcine', 'Neurologist', 'Osteopathic', 'Otolaryngologist', 'Pediatrician', 'Phlebologist', 'Pulmonologist', 'Rheumatologists', 'Tuberculosis', 'hepatologist']

In [26]:
doctor_disease["Specialist"] = (
    doctor_disease["Specialist"]
    .astype(str)
    .str.replace("\xa0", " ", regex=False)
    .str.strip()
)

print("Clean Specialist List:")
print(sorted(doctor_disease["Specialist"].unique()))

Clean Specialist List:
['Allergist', 'Cardiologist', 'Dermatologist', 'Endocrinologist', 'Gastroenterologist', 'Gynecologist', 'Hepatologist', 'Internal Medcine', 'Neurologist', 'Osteopathic', 'Otolaryngologist', 'Pediatrician', 'Phlebologist', 'Pulmonologist', 'Rheumatologists', 'Tuberculosis', 'hepatologist']

In [27]:
drug_reaction_rows = original_data[
    original_data["Disease"].str.strip().str.lower() == "drug reaction"
]

drug_reaction_rows[["Disease", "Symptom_1", "Symptom_2", "Symptom_3", "Symptom_4"]]

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4
40,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition
41,Drug Reaction,itching,stomach_pain,burning_micturition,spotting_ urination
42,Drug Reaction,itching,skin_rash,burning_micturition,spotting_ urination
43,Drug Reaction,itching,skin_rash,stomach_pain,spotting_ urination
44,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition
...,...,...,...,...,...
4719,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition
4760,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition
4801,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition
4842,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition
4883,Drug Reaction,itching,skin_rash,stomach_pain,burning_micturition

In [28]:
def recommend_specialist(predicted_disease):
    specialist = disease_to_specialist.get(predicted_disease)

    if specialist is None:
        return "Specialist mapping not available"

    return specialist


# Test
test_disease = "Acne"

print("Predicted Disease:", test_disease)
print("Recommended Specialist:", recommend_specialist(test_disease))

Predicted Disease: Acne
Recommended Specialist: Dermatologist

In [29]:
def find_available_doctors(specialist, duty_date):
    
    query = """
        SELECT
            d.doctor_name,
            d.specialization,
            dep.department_name,
            ds.shift_name,
            ds.start_time,
            ds.end_time,
            d.room_number,
            ds.status
        FROM doctor_shifts ds
        JOIN doctors d
            ON ds.doctor_id = d.doctor_id
        JOIN departments dep
            ON d.department_id = dep.department_id
        WHERE d.specialization = ?
          AND ds.duty_date = ?
          AND ds.status = 'Available'
        ORDER BY ds.start_time
    """
    
    return pd.read_sql_query(
        query,
        conn,
        params=(specialist, duty_date)
    )

In [31]:
from datetime import date

today = date.today().isoformat()

print("Today's date:", today)

Today's date: 2026-08-25

In [33]:
import sqlite3
import os

DB_PATH = os.path.join("database", "hospital.db")

conn = sqlite3.connect(DB_PATH)

print("Database connected successfully!")

Database connected successfully!

In [34]:
available_dermatologists = find_available_doctors(
    "Dermatologist",
    today
)

available_dermatologists

Empty DataFrame
Columns: [doctor_name, specialization, department_name, shift_name, start_time, end_time, room_number, status]
Index: []

In [35]:
pd.read_sql_query("""
    SELECT DISTINCT duty_date
    FROM doctor_shifts
    ORDER BY duty_date
""", conn)

    duty_date
0  2026-08-22
1  2026-08-24

In [36]:
available_dermatologists = find_available_doctors(
    "Dermatologist",
    "2026-08-24"
)

available_dermatologists

,doctor_name,specialization,department_name,shift_name,start_time,end_time,room_number,status
0,Dr. Amit Shah,Dermatologist,Dermatology,Morning,08:00,14:00,OPD-03,Available

In [37]:
def hospital_recommendation(symptoms, duty_date):
    
    # Convert symptoms into the same format used during training
    symptom_text = " ".join(
        symptom.strip().replace("_", " ")
        for symptom in symptoms
        if symptom.strip() != ""
    )
    
    # Convert symptoms into TF-IDF features
    symptom_vector = vectorizer.transform([symptom_text])
    
    # Predict disease
    predicted_disease = clean_model.predict(symptom_vector)[0]
    
    # Find specialist
    specialist = disease_to_specialist.get(
        predicted_disease,
        "Specialist mapping not available"
    )
    
    # Find available doctors
    if specialist != "Specialist mapping not available":
        doctors = find_available_doctors(
            specialist,
            duty_date
        )
    else:
        doctors = pd.DataFrame()
    
    return predicted_disease, specialist, doctors

In [38]:
symptoms = [
    "itching",
    "skin rash",
    "nodal skin eruptions"
]

predicted_disease, specialist, doctors = hospital_recommendation(
    symptoms,
    "2026-08-24"
)

print("Predicted Disease:", predicted_disease)
print("Recommended Specialist:", specialist)

print("\nAvailable Doctors:")
display(doctors)

Predicted Disease: Fungal infection
Recommended Specialist: Dermatologist

Available Doctors:

,doctor_name,specialization,department_name,shift_name,start_time,end_time,room_number,status
0,Dr. Amit Shah,Dermatologist,Dermatology,Morning,08:00,14:00,OPD-03,Available

In [2]:
import pandas as pd

disease_description = pd.read_csv(
    "data/Disease_Description.csv",
    encoding="latin1"
)

print("Rows:", disease_description.shape[0])
print("Columns:", disease_description.shape[1])

disease_description.head()

Rows: 41
Columns: 2

          Disease                                        Description
0   Drug Reaction  An adverse drug reaction (ADR) is an injury ca...
1         Malaria  An infectious disease caused by protozoan para...
2         Allergy  An allergy is an immune system response to a f...
3  Hypothyroidism  Hypothyroidism, also called underactive thyroi...
4       Psoriasis  Psoriasis is a common skin disorder that forms...

In [3]:
disease_description.columns = ["Disease", "Description"]

disease_to_description = dict(
    zip(
        disease_description["Disease"],
        disease_description["Description"]
    )
)

print("Total disease descriptions:", len(disease_to_description))

print("\nSample:")
for disease, description in list(disease_to_description.items())[:3]:
    print(f"\n{disease}:")
    print(description)

Total disease descriptions: 41

Sample:

Drug Reaction:
An adverse drug reaction (ADR) is an injury caused by taking medication. ADRs may occur following a single dose or prolonged administration of a drug or result from the combination of two or more drugs.

Malaria:
An infectious disease caused by protozoan parasites from the Plasmodium family that can be transmitted by the bite of the Anopheles mosquito or by a contaminated needle or transfusion. Falciparum malaria is the most deadly type.

Allergy:
An allergy is an immune system response to a foreign substance that's not typically harmful to your body.They can include certain foods, pollen, or pet dander. Your immune system's job is to keep you healthy by fighting harmful pathogens.

In [4]:
def complete_recommendation(symptoms, duty_date):

    # Convert symptoms to text
    symptom_text = " ".join(
        symptom.strip().replace("_", " ")
        for symptom in symptoms
        if symptom.strip() != ""
    )

    # Convert symptoms into TF-IDF features
    symptom_vector = vectorizer.transform([symptom_text])

    # Predict disease
    predicted_disease = clean_model.predict(symptom_vector)[0]

    # Get disease description
    description = disease_to_description.get(
        predicted_disease,
        "Description not available"
    )

    # Get specialist
    specialist = disease_to_specialist.get(
        predicted_disease,
        "Specialist mapping not available"
    )

    # Find available doctors
    if specialist != "Specialist mapping not available":
        doctors = find_available_doctors(
            specialist,
            duty_date
        )
    else:
        doctors = pd.DataFrame()

    return predicted_disease, description, specialist, doctors

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_clean = vectorizer.fit_transform(df_clean["All_Symptoms"])

print("Vectorizer ready!")
print("X_clean shape:", X_clean.shape)

NameError: name 'df_clean' is not defined

In [5]:
symptoms = [
    "itching",
    "skin rash",
    "nodal skin eruptions"
]

predicted_disease, description, specialist, doctors = complete_recommendation(
    symptoms,
    "2026-08-24"
)

print("Predicted Disease:", predicted_disease)

print("\nDisease Description:")
print(description)

print("\nRecommended Specialist:", specialist)

print("\nAvailable Doctors:")
display(doctors)

NameError: name 'vectorizer' is not defined

In [8]:
import pandas as pd

original_data = pd.read_csv(
    "data/Original_Dataset.csv",
    encoding="latin1"
)

print("Dataset loaded successfully!")
print("Rows:", original_data.shape[0])
print("Columns:", original_data.shape[1])

Dataset loaded successfully!
Rows: 4920
Columns: 18

In [9]:
symptom_columns = [
    col for col in original_data.columns
    if col.startswith("Symptom_")
]

df_ml = original_data.copy()

df_ml["All_Symptoms"] = df_ml[symptom_columns].fillna("").apply(
    lambda row: " ".join(
        str(x).strip().replace("_", " ")
        for x in row
        if str(x).strip() != ""
    ),
    axis=1
)

df_clean = df_ml.drop_duplicates(
    subset=["Disease", "All_Symptoms"]
).reset_index(drop=True)

print("Original records:", len(df_ml))
print("Clean records:", len(df_clean))

Original records: 4920
Clean records: 304

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

vectorizer = TfidfVectorizer()

X_clean = vectorizer.fit_transform(df_clean["All_Symptoms"])
y_clean = df_clean["Disease"]

X_train_clean, X_test_clean, y_train_clean, y_test_clean = train_test_split(
    X_clean,
    y_clean,
    test_size=0.20,
    random_state=42,
    stratify=y_clean
)

clean_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

clean_model.fit(X_train_clean, y_train_clean)

print("Clean model trained successfully!")
print("Training records:", X_train_clean.shape[0])
print("Testing records:", X_test_clean.shape[0])

Clean model trained successfully!
Training records: 243
Testing records: 61

In [11]:
import sqlite3
import os

DB_PATH = os.path.join("database", "hospital.db")
conn = sqlite3.connect(DB_PATH)

print("Database connected successfully!")

Database connected successfully!

In [12]:
# Load Disease → Specialist mapping
doctor_disease = pd.read_csv(
    "data/Doctor_Versus_Disease.csv",
    encoding="latin1"
)

doctor_disease.columns = ["Disease", "Specialist"]

doctor_disease["Disease"] = doctor_disease["Disease"].astype(str).str.strip()
doctor_disease["Specialist"] = (
    doctor_disease["Specialist"]
    .astype(str)
    .str.replace("\xa0", " ", regex=False)
    .str.strip()
)

disease_to_specialist = dict(
    zip(
        doctor_disease["Disease"],
        doctor_disease["Specialist"]
    )
)

# Load Disease → Description mapping
disease_description = pd.read_csv(
    "data/Disease_Description.csv",
    encoding="latin1"
)

disease_description.columns = ["Disease", "Description"]

disease_description["Disease"] = (
    disease_description["Disease"].astype(str).str.strip()
)

disease_to_description = dict(
    zip(
        disease_description["Disease"],
        disease_description["Description"]
    )
)

print("Disease → Specialist:", len(disease_to_specialist))
print("Disease → Description:", len(disease_to_description))

Disease → Specialist: 40
Disease → Description: 41

In [13]:
def find_available_doctors(specialist, duty_date):

    query = """
        SELECT
            d.doctor_name,
            d.specialization,
            dep.department_name,
            ds.shift_name,
            ds.start_time,
            ds.end_time,
            d.room_number,
            ds.status
        FROM doctor_shifts ds
        JOIN doctors d
            ON ds.doctor_id = d.doctor_id
        JOIN departments dep
            ON d.department_id = dep.department_id
        WHERE d.specialization = ?
          AND ds.duty_date = ?
          AND ds.status = 'Available'
        ORDER BY ds.start_time
    """

    return pd.read_sql_query(
        query,
        conn,
        params=(specialist, duty_date)
    )

print("Doctor search function ready!")

Doctor search function ready!

In [14]:
def complete_recommendation(symptoms, duty_date):

    # Convert symptoms into text
    symptom_text = " ".join(
        symptom.strip().replace("_", " ")
        for symptom in symptoms
        if symptom.strip() != ""
    )

    # Convert symptoms into TF-IDF features
    symptom_vector = vectorizer.transform([symptom_text])

    # Predict disease
    predicted_disease = clean_model.predict(symptom_vector)[0]

    # Get disease description
    description = disease_to_description.get(
        predicted_disease,
        "Description not available"
    )

    # Get specialist
    specialist = disease_to_specialist.get(
        predicted_disease,
        "Specialist mapping not available"
    )

    # Find available doctors
    if specialist != "Specialist mapping not available":
        doctors = find_available_doctors(
            specialist,
            duty_date
        )
    else:
        doctors = pd.DataFrame()

    return predicted_disease, description, specialist, doctors

print("Complete recommendation function ready!")

Complete recommendation function ready!

In [15]:
symptoms = [
    "itching",
    "skin rash",
    "nodal skin eruptions"
]

predicted_disease, description, specialist, doctors = complete_recommendation(
    symptoms,
    "2026-08-24"
)

print("Predicted Disease:", predicted_disease)

print("\nDisease Description:")
print(description)

print("\nRecommended Specialist:", specialist)

print("\nAvailable Doctors:")
display(doctors)

Predicted Disease: Fungal infection

Disease Description:
In humans, fungal infections occur when an invading fungus takes over an area of the body and is too much for the immune system to handle. Fungi can live in the air, soil, water, and plants. There are also some fungi that live naturally in the human body. Like many microbes, there are helpful fungi and harmful fungi.

Recommended Specialist: Dermatologist

Available Doctors:

,doctor_name,specialization,department_name,shift_name,start_time,end_time,room_number,status
0,Dr. Amit Shah,Dermatologist,Dermatology,Morning,08:00,14:00,OPD-03,Available

In [16]:
# Check existing database tables

tables = pd.read_sql_query("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
""", conn)

tables

              name
0     appointments
1      departments
2    doctor_shifts
3          doctors
4  patient_history
5         patients
6         services
7  sqlite_sequence

In [17]:
appointment_columns = pd.read_sql_query("""
    PRAGMA table_info(appointments)
""", conn)

appointment_columns

   cid              name     type  notnull dflt_value  pk
0    0    appointment_id  INTEGER        0       None   1
1    1        patient_id  INTEGER        1       None   0
2    2         doctor_id  INTEGER        1       None   0
3    3  appointment_date     TEXT        1       None   0
4    4  appointment_time     TEXT        1       None   0
5    5            status     TEXT        1       None   0
6    6            reason     TEXT        0       None   0

In [18]:
patient_columns = pd.read_sql_query("""
    PRAGMA table_info(patients)
""", conn)

patient_columns

   cid               name     type  notnull dflt_value  pk
0    0         patient_id  INTEGER        0       None   1
1    1       patient_name     TEXT        1       None   0
2    2                age  INTEGER        0       None   0
3    3             gender     TEXT        0       None   0
4    4              phone     TEXT        0       None   0
5    5            address     TEXT        0       None   0
6    6           symptoms     TEXT        0       None   0
7    7  registration_date     TEXT        0       None   0

In [19]:
patients = pd.read_sql_query("""
    SELECT
        patient_id,
        patient_name,
        age,
        gender,
        phone
    FROM patients
    ORDER BY patient_id
""", conn)

patients

   patient_id    patient_name  age  gender       phone
0           1     Aarav Patil   25    Male  9876500001
1           2      Sneha More   32  Female  9876500002
2           3     Rohan Joshi   45    Male  9876500003
3           4  Priya Kulkarni    8  Female  9876500004
4           5      Amit Desai   55    Male  9876500005

In [20]:
amit_doctor = pd.read_sql_query("""
    SELECT
        doctor_id,
        doctor_name,
        specialization
    FROM doctors
    WHERE doctor_name = 'Dr. Amit Shah'
""", conn)

amit_doctor

   doctor_id    doctor_name specialization
0          3  Dr. Amit Shah  Dermatologist
1         13  Dr. Amit Shah  Dermatologist

In [21]:
pd.read_sql_query("""
    SELECT
        d.doctor_id,
        d.doctor_name,
        d.specialization,
        ds.shift_name,
        ds.start_time,
        ds.end_time,
        ds.duty_date,
        ds.status
    FROM doctors d
    JOIN doctor_shifts ds
        ON d.doctor_id = ds.doctor_id
    WHERE d.doctor_name = 'Dr. Amit Shah'
      AND ds.duty_date = '2026-08-24'
    ORDER BY d.doctor_id
""", conn)

,doctor_id,doctor_name,specialization,shift_name,start_time,end_time,duty_date,status
0,3,Dr. Amit Shah,Dermatologist,Morning,08:00,14:00,2026-08-24,Available

In [22]:
appointment_date = "2026-08-24"
appointment_time = "10:00"

cursor = conn.cursor()

cursor.execute("""
    INSERT INTO appointments (
        patient_id,
        doctor_id,
        appointment_date,
        appointment_time,
        status,
        reason
    )
    VALUES (?, ?, ?, ?, ?, ?)
""", (
    1,
    3,
    appointment_date,
    appointment_time,
    "Booked",
    "Fungal infection"
))

conn.commit()

print("Appointment booked successfully!")
print("Appointment ID:", cursor.lastrowid)

Appointment booked successfully!
Appointment ID: 6

In [23]:
appointment_check = pd.read_sql_query("""
    SELECT
        a.appointment_id,
        p.patient_name,
        d.doctor_name,
        d.specialization,
        a.appointment_date,
        a.appointment_time,
        a.status,
        a.reason
    FROM appointments a
    JOIN patients p
        ON a.patient_id = p.patient_id
    JOIN doctors d
        ON a.doctor_id = d.doctor_id
    WHERE a.appointment_id = 6
""", conn)

appointment_check

,appointment_id,patient_name,doctor_name,specialization,appointment_date,appointment_time,status,reason
0,6,Aarav Patil,Dr. Amit Shah,Dermatologist,2026-08-24,10:00,Booked,Fungal infection

In [24]:
symptom_weights = pd.read_csv(
    "data/Symptom_Weights.csv",
    encoding="latin1"
)

print("Rows:", symptom_weights.shape[0])
print("Columns:", symptom_weights.shape[1])

symptom_weights.head(10)

Rows: 130
Columns: 2

           abdominal_pain   1
0   abnormal_menstruation   2
1                 acidity   3
2     acute_liver_failure   4
3       altered_sensorium   5
4                 anxiety   6
5               back_pain   7
6              belly_pain   8
7              blackheads   9
8      bladder_discomfort  10
9                 blister  11

In [25]:
symptom_weights = pd.read_csv(
    "data/Symptom_Weights.csv",
    header=None,
    names=["Symptom", "Weight"],
    encoding="latin1"
)

# Clean symptom names
symptom_weights["Symptom"] = (
    symptom_weights["Symptom"]
    .astype(str)
    .str.strip()
    .str.replace("_", " ", regex=False)
)

print("Total symptoms:", len(symptom_weights))
print("\nSample:")
display(symptom_weights.head(10))

Total symptoms: 131

Sample:

                 Symptom  Weight
0         abdominal pain       1
1  abnormal menstruation       2
2                acidity       3
3    acute liver failure       4
4      altered sensorium       5
5                anxiety       6
6              back pain       7
7             belly pain       8
8             blackheads       9
9     bladder discomfort      10

In [26]:
history = pd.read_sql_query("""
    SELECT *
    FROM patient_history
    ORDER BY history_id
""", conn)

history

,history_id,patient_id,doctor_id,visit_date,department,symptoms,notes
0,1,1,3,2026-08-20,Dermatology,skin itching and red rashes,Skin examination advised
1,2,2,10,2026-08-18,Gastroenterology,stomach pain and digestive problem,Dietary consultation advised
2,3,3,4,2026-08-15,Orthopedics,joint pain and difficulty walking,Physical examination advised
3,4,4,6,2026-08-21,Pediatrics,fever and cough,General check-up completed
4,5,5,2,2026-08-19,Cardiology,chest pain and breathing difficulty,Cardiology consultation advised

In [27]:
def get_patient_history(patient_id):

    query = """
        SELECT
            h.history_id,
            p.patient_name,
            d.doctor_name,
            h.visit_date,
            h.department,
            h.symptoms,
            h.notes
        FROM patient_history h
        JOIN patients p
            ON h.patient_id = p.patient_id
        JOIN doctors d
            ON h.doctor_id = d.doctor_id
        WHERE h.patient_id = ?
        ORDER BY h.visit_date DESC
    """

    return pd.read_sql_query(
        query,
        conn,
        params=(patient_id,)
    )

print("Patient history function ready!")

Patient history function ready!

In [28]:
patient_history = get_patient_history(1)

print("Patient History:")
display(patient_history)

Patient History:

,history_id,patient_name,doctor_name,visit_date,department,symptoms,notes
0,1,Aarav Patil,Dr. Amit Shah,2026-08-20,Dermatology,skin itching and red rashes,Skin examination advised

In [29]:
import pickle

with open("model/disease_model.pkl", "wb") as f:
    pickle.dump(clean_model, f)

with open("model/vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

print("Model and vectorizer saved successfully!")

Model and vectorizer saved successfully!

In [30]:
import os

print("Model exists:", os.path.exists("model/disease_model.pkl"))
print("Vectorizer exists:", os.path.exists("model/vectorizer.pkl"))

print("\nModel folder:")
print(os.listdir("model"))

Model exists: True
Vectorizer exists: True

Model folder:
['.ipynb_checkpoints', 'disease_model.pkl', 'hospital management.ipynb', 'vectorizer.pkl']

In [4]:
import sqlite3

conn = sqlite3.connect("hospital.db")

print("Database connected successfully!")

Database connected successfully!

In [5]:
print("doctor_shifts columns:")
print(pd.read_sql_query("PRAGMA table_info(doctor_shifts)", conn))

doctor_shifts columns:
Empty DataFrame
Columns: [cid, name, type, notnull, dflt_value, pk]
Index: []

In [6]:
print(pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table'",
    conn
))

Empty DataFrame
Columns: [name]
Index: []

In [7]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\DELL\PythonLibraries\hospital management and recommendation system
['.ipynb_checkpoints', 'app.py', 'data', 'database', 'hospital management.ipynb', 'hospital.db', 'model']

In [8]:
import os

print(os.listdir("database"))

['hospital.db']

In [2]:
import sqlite3

conn = sqlite3.connect("database/hospital.db")

print("Correct database connected!")

Correct database connected!

In [3]:
print(pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table'",
    conn
))

NameError: name 'pd' is not defined

In [4]:
print(pd.read_sql_query(
    "PRAGMA table_info(doctor_shifts)",
    conn
))

NameError: name 'pd' is not defined

In [5]:
print(pd.read_sql_query(
    "PRAGMA table_info(doctors)",
    conn
))

NameError: name 'pd' is not defined

In [6]:
pd.read_sql_query(
    """
    SELECT
        d.doctor_name,
        d.specialization,
        ds.duty_date,
        ds.shift_name,
        ds.start_time,
        ds.end_time,
        d.room_number,
        ds.status
    FROM doctor_shifts ds
    JOIN doctors d
        ON ds.doctor_id = d.doctor_id
    """,
    conn
)

NameError: name 'pd' is not defined

In [7]:
pd.read_sql_query(
    """
    SELECT
        d.doctor_name,
        d.specialization,
        ds.duty_date,
        ds.shift_name,
        ds.start_time,
        ds.end_time,
        d.room_number,
        ds.status
    FROM doctor_shifts ds
    JOIN doctors d
        ON ds.doctor_id = d.doctor_id
    WHERE LOWER(d.specialization) LIKE '%endocrin%'
    """,
    conn
)

NameError: name 'pd' is not defined

In [8]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("hospital.db")

In [9]:
pd.read_sql_query(
    """
    SELECT *
    FROM patient_history
    """,
    conn
)

DatabaseError: Execution failed on sql '
    SELECT *
    FROM patient_history
    ': no such table: patient_history

In [10]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("database/hospital.db")

print(pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table'",
    conn
))

              name
0      departments
1  sqlite_sequence
2          doctors
3    doctor_shifts
4         patients
5  patient_history
6     appointments
7         services

In [11]:
pd.read_sql_query(
    """
    SELECT *
    FROM patient_history
    """,
    conn
)

,history_id,patient_id,doctor_id,visit_date,department,symptoms,notes
0,1,1,3,2026-08-20,Dermatology,skin itching and red rashes,Skin examination advised
1,2,2,10,2026-08-18,Gastroenterology,stomach pain and digestive problem,Dietary consultation advised
2,3,3,4,2026-08-15,Orthopedics,joint pain and difficulty walking,Physical examination advised
3,4,4,6,2026-08-21,Pediatrics,fever and cough,General check-up completed
4,5,5,2,2026-08-19,Cardiology,chest pain and breathing difficulty,Cardiology consultation advised